### ISSUE TITLE
Issue with manga sorting

### ISSUE THREAD

**Issue by Small-tailqwq** [Utazukin/Ichaival#42] opened 2023-03-12 17:15 UTC
I am currently using your software and I want to express my gratitude for your open source contribution. However, I have encountered an issue while using your software. It seems that some manga with the same title but different numbers are sorted based on text rather than numbers. For example, manga 1, 10, 11 should be sorted as 1-10-11, but the software may sort them as 10-1-11. However, this issue does not exist in the web version of lanraragi.

If I want to rename my manga, it may take some time and it won't solve the problem permanently. Therefore, I hope you can fix this issue if possible. Thank you for your time and effort.

**Comment by Albireo6972** [comment] 2023-03-14 01:09
I have a suggestion you may not like, because it does require renaming the items labeled as 1 to 9.  If you add a 0 to the beginning of the number, so for example 1 becomes 01, then it should sort correctly. Padding the number should help to fix the issue, but I can absolutely understand the want to not do that. Just wanted to throw the option out there.

**Comment by Small-tailqwq** [comment] 2023-03-14 01:20
> I have a suggestion you may not like, because it does require renaming the items labeled as 1 to 9. If you add a 0 to the beginning of the number, so for example 1 becomes 01, then it should sort correctly. Padding the number should help to fix the issue, but I can absolutely understand the want to not do that. Just wanted to throw the option out there.

In fact I did that, I downloaded about 600 manga, so I needed four digits to sort them correctly, for example manga 1 I should name 0001, manga 10 I should name 0010, manga 100 I should name 0100. but after I imported the named manga into lanraragi, I found that it automatically changed my naming to 1, 10, 100 I have to change the name of the manga metadata in lanraragi if I want to get the sorting right. You know, that's a million times harder than changing the filename. So I gave up using this app for now, because I found two other problems.
If the strip is saved in pdf (webcomic, the long kind), it has a few pictures that may fail to load, while in zip it doesn't, and in lanraragi web version neither pdf nor zip does.
If there are too many comics in one comic category, it may not be able to load out any of them in the app. (For example, I put all my 600+ manga in one category to distinguish them from the same manga, but I can't see any of them on the app, so I may have to wait for all the manga to finish loading before they can be displayed. This is not the case with the web version either)
To be honest, I should return to my old job, using this software to read homo sapiens is really very convenient, all the functions are there, but reading manga (especially web serial manga) may not be so convenient. But thank you for all your efforts and suggestions, thanks nyan~

Translated with www.DeepL.com/Translator (free version)

**Comment by Utazukin** [comment] 2023-04-01 17:05
Title sort now matches the web version.  I wasn't able to reproduce the category issue on my end.  The pdf issue might be fixed by using the "Force Refresh" option which will wait for all the images to finish being extracted before trying to load them.

**Closed as completed by Utazukin** 2023-04-01 17:05 UTC
